### ISSUE TITLE
Value sensor settings open during a save can't be closed after loading the save.

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/evoGUI#28]
What the title says. If you save the game with a sensor settings GUI open (e.g., the play_time sensor settings), then later load that save, you will not be able to make the sensor settings GUI go away without console hax (`/c game.local_player.gui.center.[sensor_name]_settings.destroy()`).

This is very unfriendly and needs to stop now.

**Comment by narc0tiq** [comment]
The whole thing is an artifact of how the `evogui.on_click` table gets built up (wherein attachments are made only when the GUI is created, and obviously after loading a save with the GUI already visible, it ain't getting created anymore). I'm surprised nobody other than jocker-il has reported this yet.

The fix is to have all `on_click` handlers registered permanently; where this involves a sensor name it should probably be done as part of `ValueSensor.new` (since the parts other than the sensor name are constants).

**Comment by Afforess** [comment]
I looked into this issue, and it seems a bit worse than even what you describe. Right now evogui.on_cllick is a global object that has event handlers for gui elements, and these handlers, when they are currently created, are player specific. So in Multiplayer, if 2 players each open settings up, whoever opened them last will have the event handler set, and the first player is screwed.

**Comment by narc0tiq** [comment]
Yeah, I definitely didn't know what I was doing when I wrote the EvoGUI event handlers, and trying to keep tacking on to them has led to some real nasties. I think something more like [YARM's handlers](https://github.com/narc0tiq/YARM/blob/abaa257/resmon.lua#L684) would be better -- they expect to have to figure out which player they belong to, and all the other relevant parts.

Thanks for digging into it.
