### ISSUE TITLE
New sensor: wind speed / direction

### ISSUE THREAD

**Issue by StephanSteinert** [narc0tiq/evoGUI#56]
Hello, 

i would like to see a windspeed sensor - see https://forums.factorio.com/viewtopic.php?f=92&t=13837&start=110#p149880

Greetings

**Comment by narc0tiq** [comment]
Sounds good to me.

**Comment by StephanSteinert** [comment]
Added a remote sensor for this in the meanwhile: https://forums.factorio.com/viewtopic.php?f=92&t=26033

**Comment by narc0tiq** [comment]
Why not pull request it into EvoGUI proper? I don't bite, I promise.

**Comment by StephanSteinert** [comment]
I have no idea how this works.
I can send you / you can copy the code if you want, but it's not multiplayer and multisurface safe.
