### ISSUE TITLE
Error with Evo GUI mod

### ISSUE THREAD

**Issue by Sploshman** [narc0tiq/evoGUI#57]
![image](https://cloud.githubusercontent.com/assets/19254587/15099879/28526846-156b-11e6-89ff-3e9a8e8d523f.png)

**Comment by narc0tiq** [comment]
Okay, that's very weird. What version of EvoGUI is this? What did you do before this happened? Does it stop happening if you tell the pollution sensor to be always visible?

**Comment by narc0tiq** [comment]
Lacking any kind of feedback, I'm going to assume you resolved it yourself. Please feel free to reopen if that is not the case.
