### ISSUE TITLE
Remove mod name from remote sensor display names on the settings screen.

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/evoGUI#59]
(via <https://forums.factorio.com/viewtopic.php?p=158391#p158391>)

If we want to separate them from the built-in sensors, we might put "[addon]" in there somewhere, but I'm not sure the difference matters at all to the player.

Note: at least one mod that registers a remote sensor (namely, [Rescaled-Evolution-Factor](https://forums.factorio.com/viewtopic.php?f=91&t=21215)) is passing a `mod_name` different from its actual mod name, presumably because of the behaviour we're about to change. This likely results in people thinking "EvoGUI sucks because it didn't notice I removed that mod and left its sensor behind but it doesn't do anything".

**Comment by StephanSteinert** [comment]
Hello,

seems not to work because the caption is not shown in settings.
My init: 
remote.call("EvoGUI", "create_remote_sensor", { mod_name = "steinios_research_sensor",
													name = "steinio_rs", 
													text = "Current research: none " .. "(-%)", 
													caption = "Current research" 
												}
