### ISSUE TITLE
Player location value sensor is off by one for negative positions.

### ISSUE THREAD

**Issue by credomane** [narc0tiq/evoGUI#67]
I was messing around with the chunk grid on and with evoGUI showing player coords. Happened to notice that the chunk division wasn't lining up with where evoGUI said I was.

The experimentation that followed revealed whatever coordinate is negative evoGUI will be off by 1 for that coordinate.

I'm thinking that `string.format()` isn't playing nice with negative numbers. It is making the 0,0 tile appear as if it is a special 2 by 2 tile. lol

Changed my local copy with some math.floor and everything lined up on positive and negative sides.

OLD:
```lua
string.format('@%d, %d', p.position.x, p.position.y)
```

NEW:
```lua
string.format('@%d, %d', math.floor(p.position.x), math.floor(p.position.y))
```
This is the file and line number https://github.com/narc0tiq/evoGUI/blob/master/value_sensors/player_locations.lua#L129

**Comment by narc0tiq** [comment]
What a weird and wonderful bug. Thank you for the report, and the fix.
