### ISSUE TITLE
0.15.22 error

### ISSUE THREAD

**Issue by Southpaw018** [narc0tiq/evoGUI#72]
0.15.22 throws a console error message on each update:
`[EvoGUI|on_tick:update_gui]Error:  __EvoGUI__/evoGUI.lua:101:attempt to index field 'evogui' (a nil value)`

**Comment by narc0tiq** [comment]
Yup, also reported in #71. I'm mobile at the moment, and it's late here, so the fix will have to wait until tomorrow. But thank you for the report!

**Comment by Southpaw018** [comment]
Sorry! I checked the issue list before I started typing, but got beat to it anyway. Thanks for the updates in advance :)

**Comment by narc0tiq** [comment]
Not a problem.
