### ISSUE TITLE
Error since most recent Factorio 15 update

### ISSUE THREAD

**Issue by brehmluke** [narc0tiq/evoGUI#73]
When I opened my save the following message started appearing once every second.
[EvoGUI|on_tick:update_gui] Error: __EvoGUI__/evoGUI.lua:101 attempt to index field 'evoGUI' (a nil value)
Everything was working great last night

**Comment by brehmluke** [comment]
I read your comment on the previous report of this issue. Enjoy your night!

**Comment by dgw** [comment]
I propose closing this as a duplicate of #71. Sounds like we'll get a fix ASAP anyway. :)

**Comment by narc0tiq** [comment]
Indeed. I'll get to it sometime today, whenever I'm actually at a computer. Follow #71 for updates.
